### PR TITLE
Update index.html tab icon 

### PR DESCRIPTION
**Pull request by suryablaster**

### CODE REVIEW

**Comment by priyansh32** [comment]
Hey @suryablaster, Thank you for the PR 
usually, when you work on an open-source repo you should first get the issue assigned to you, or someone else may be working on the same issue and we may not know. 🙌🏼

**Comment by Ranjana-Kambhammettu** [comment]
This is not quite right. 

This is the format for adding an icon to the browser tab:

```<link rel="icon" href="http://example.com/favicon.png">```

**Review by Ranjana-Kambhammettu — COMMENTED** [review]
This is not quite right.

This is the format for adding an icon to the browser tab:

```<link rel="icon" href="http://example.com/favicon.png">```

**Comment by priyansh32** [comment]
We are only accepting contributions from NITK students for now. 😃

**Pull request closed without merging**
